### ISSUE TITLE
Missing CONTRIBUTING.md file or instructions how to set up project

### ISSUE THREAD

**Issue by berserkingyadis** [collinsmith/riiablo#6]
This repo is missing a "how to get started" kind of file or a new section in the main readme file. 

How can ppl get this running to contribute code? What does one need to install to contribute?

**Comment by collinsmith** [comment]
I don't think it's ready just yet, partly because I may make some sweeping changes soon. This is a learning process for me, but portions of the code base are beginning to stabilize.

FYI, I've been using IntelliJ IDEA 2018.1.5 Community Edition for development, and I am not aware of any machine-specific environment changes that need to be made to build and run it in Single Player (Multiplayer is a bit more complicated). Eventually I'll add some kind of auto building tool to make it easier for people who just want to run it. Just make sure `-home` is set in program args pointing at your Diablo II installation directory (with the MPQ archives) and the working dir is set to `\android\assets` for the desktop launcher. If you can't get it to work, I guess you'll just have to wait until I can write better instructions when the project is a bit further along.

**Comment by needo2** [comment]
I've managed to run it with IntelliJ without android sdk with JDK8 by removing build.gradle from android folder and project(":android") from root build.gradle

If you want very streamlined and no hassle process you can just install Android Studio and anything that comes with it and run the desktop version

**Comment by collinsmith** [comment]
Setting up building on Android is a bit of a hassle in IntelliJ, Android Studio might be easier for some (personally, I use IntelliJ for all modules, but I've used AS in the past). I don't suggest running the Android version just yet anyways, as I would like to make some more optimizations.

Aside, minus some minor loading issues not obvious in the desktop version, it does run quite well with the new renderer allowing 10 ms frame times on a 4 year old phone, so I am optimistic.

**Comment by berserkingyadis** [comment]
Hey Thanks for taking care of this issue! With these steps more people will be able to build and hopefully contribute :)
